# Generated by Django 5.2.9 on 2025-12-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pack_profile_usercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
