# Generated by Django 5.2.9 on 2026-01-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_card_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserCard',
        ),
    ]
