# Generated by Django 5.2.9 on 2026-01-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_coins_delete_usercard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
